### ISSUE TITLE
last fm only scrobbles last item played by an artist

### ISSUE THREAD

**Issue by bigmittens** [mopidy/mopidy-scrobbler#19] opened 2016-02-29 03:23 UTC
for example, when playing an album by an artist, viewing the last.fm page during will display the current song, but when it goes to the next song it wont have scrobbled the past one.

happens when playing local music.

**Comment by jamesbvaughan** [comment] 2016-03-01 02:35
I'm experiencing this as well. If I have time to give it a go next week, I may try to fix this.

**Comment by jodal** [comment] 2016-03-01 12:33
This is a duplicate of mopidy/mopidy#1456. Closing this one, as the problem is in Mopidy, not Mopidy-Scrobbler.

**Closed by jodal** 2016-03-01 12:33 UTC
